import './globals.css';
import ProviderWrapper from '../redux/provider';



export const metadata = {
  title: 'Memo Shish Kebab | Manhattan',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          {children}        
         </ProviderWrapper>
      </body>
    </html>
  )
}
