name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Remote Docker
      uses: appleboy/ssh-action@master
      with:
        host: 54.224.3.158
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: 22
    - name: Upload project files to server
      uses: actions/upload-artifact@v2
      with:
        name: project-files
        path: ${{ github.workspace }}
    - name: Install dependencies and build project
      run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /path/to/your/project && npm install && npm run build"
    - name: Restart Nginx server
      run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo systemctl restart nginx"
