name: Deploy to Remote Server
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v2
    - name: Deploy to Remote Server
      uses: easingthemes/ssh-deploy@v2.2.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete -v"
      with:
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        SOURCE: "."
        TARGET: ${{ secrets.SERVER_DIR }}
