name: Deploy to Server

on:
  push:
    branches:
      - main

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

defaults:
  run:
    shell: bash
    working-directory: ${{ github.workspace }}

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy to Remote Server
      uses: agshinmammadov/ssh-deploy@v2.2.7
      with:
        ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        remote_host: ${{ secrets.SERVER_IP }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        source: ./
        target: /var/www/mywebsite.com/
        args: "-rltgoDzvO --delete -v"
